language: python
dist: bionic

cache:
  - pip

python:
  - '3.7'
  - '2.7'

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    update: true
    packages:
      - libstdc++6

install:
  - pip install --upgrade pip setuptools wheel
  - pip install .[all]

script:
  - pip install hacking pytest
  - flake8 .
  - pytest -v tests

sudo: false

branches:
  only:
    - master
